services:
  - type: web
    name: heo-ventas-sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: TZ
        value: America/Santiago
